# = jetty_path key
# each environment can have a jetty_path with absolute or relative
# (to app root) path to a jetty/solr install. This is used
# by the rake tasks that start up solr automatically for testing
# and by rake solr:marc:index.  
#
# jetty_path is not used by a running Blacklight application
# at all. In general you do NOT need to deploy solr in Jetty, you can deploy it
# however you want.  
# jetty_path is only required for rake tasks that need to know
# how to start up solr, generally for automated testing. 

development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/#TENANT#-public" %>
  # url: <%= ENV['SOLR_URL'] || "https://webapps.cspace.berkeley.edu/solr/#TENANT#-public" %>
  #url: <%= ENV['SOLR_URL'] || "https://apis.berkeley.edu/uat/cspace/v1/artifacts/#TENANT#-public" %>
  # nb: access via the api-central api using basicauth does not work yet: need to make a small change
  # in the configuration at api central to allow access to at least the select and suggest endpoints, and not
  # hide the endpoint completeley as we are doing now.
  #url: <%= ENV['SOLR_URL'] || "https://99999999:9999999999999999999@apis.berkeley.edu/uat/cspace/v1/artifacts/#TENANT#-public" %>
  # "app_id: 99999999"  "app_key: 9999999999999999999" get these from api-central or someone who has
  # calnet access to api-central.
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/#TENANT#-public" %>
production:
  adapter: solr
  # url: <%= ENV['SOLR_URL'] || "https://webapps-dev.cspace.berkeley.edu/solr/#TENANT#-public" %>
  url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/#TENANT#-public" %>
  GLOBAL_ALERTS: <%= true %>
